Create GCD and LCM.md
WeBeginners-Community/DocBook pull request #38
Opened 2023-01-04 07:25 UTC by Shubh08am

# Description
We are given two numbers. We need to find there greatest common divisor (GCD) and least common divisor (LCM) Using Recursion.

Fixes:  #(issue no.) 37

## Type of change

 - [✓ ] New feature (non-breaking change which adds functionality)
 
# Checklist:

- [✓ ] I have made this from my own
 - [✓ ] My code follows the style guidelines of this project
- [ ✓] I have performed a self-review of my own code
- [✓ ] I have commented my code, particularly in hard-to-understand areas
- [ ✓] I have made corresponding changes to the documentation
- [ ✓] My changes generate no new warnings

2023-01-05 17:41 UTC, Sulagna-Dutta-Roy requested changes
This is a documentation repo. Please add details

2023-01-05 18:33 UTC, Shubh08am commented
> This is a documentation repo. Please add details

I have added the documentation in detail please see it.

2023-01-05 19:38 UTC, Sulagna-Dutta-Roy commented
Checking

2023-01-06 19:00 UTC, Sulagna-Dutta-Roy approved these changes

2023-01-06 19:01 UTC, merged