create radix.md
WeBeginners-Community/DocBook pull request #42
Opened 2023-01-05 17:23 UTC by apoorva1823000

Created a readme file for radix sort with code in java language

# Description

In the folder of algorithms I added radix sort algorithm with code in java language as well as description of the sorting method

Fixes:  #22 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
<img width="524" alt="radix" src="https://user-images.githubusercontent.com/71769587/210842191-0dfde428-f6cd-48df-b2f2-fe6965f47aff.png">

2023-01-05 17:45 UTC, Sulagna-Dutta-Roy requested changes
Project folder name should be 'Radix Sort'

2023-01-05 17:50 UTC, apoorva1823000 commented
How do I change the name ?

2023-01-06 18:54 UTC, Sulagna-Dutta-Roy approved these changes

2023-01-06 18:58 UTC, Sulagna-Dutta-Roy approved these changes

2023-01-06 18:59 UTC, merged